# Generated by Django 6.0 on 2025-12-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_alter_cartitem_unique_together_cartitem_combo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='pizza_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(default=0, max_length=200, verbose_name='Название товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('pizza', 'Пицца'), ('combo', 'Комбо')], default=0, max_length=10, verbose_name='Тип товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=10, verbose_name='Размер'),
        ),
    ]
