# Generated by Django 6.0 on 2025-12-21 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0002_remove_orderitem_price_remove_pizza_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'pizza', 'size')},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzeria.combo', verbose_name='Комбо'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_type',
            field=models.CharField(choices=[('pizza', 'Пицца'), ('combo', 'Комбо')], default=0, max_length=10, verbose_name='Тип товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzeria.pizza', verbose_name='Пицца'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, choices=[('30', '30 см'), ('35', '35 см'), ('40', '40 см')], default='30', max_length=10, verbose_name='Размер'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'combo'), ('cart', 'pizza', 'size')},
        ),
    ]
